### ISSUE TITLE
Arch linux: rofimoji does not copy/paste/insert selected emoji on KDE and Wayland

### ISSUE THREAD

**Issue by tobiasKaminsky** [fdw/rofimoji#132]
I used X11 previously and it worked fine.
Since I switched to a new graphic card I can now use Wayland and now I cannot use rofimoji anylonger.
I searched quite some time across internet and also here in closed bugs, and tried lots of things, but nothing works.

I have a shortcut on KDE to open a script:
```
#!/bin/zsh

rofimoji --action clipboard --clipboarder wl-copy
```

This then shows rofimoji, where I can select any emoji and then nothing happens.
It is not in clipboard, I cannot paste it via ctrl+v, it is not typed directly.
I tested it in various windows: kwrite, yakuake, firefox, libreoffice writer

I also changed options how to call rofimoji.
I feel a bit stupid, as it is always stated that it works out of the box…

I saw that some suggested to use wtype, but this fails on konsole with:
$ wtype 23                                   
Compositor does not support the virtual keyboard protocol

Many thanks for this great project!

**Comment by fdw** [comment]
I don't have a lot of experience with Wayland, sorry. It seems that KDE does not support the necessary protocol for `wtype`, just like the error message said: https://github.com/atx/wtype/issues/34

Regarding `wl-copy`, could you please try to call it manually and see if that works? I think `echo 👌 | wl-copy` should do it.

Also, if you have suggestions for other apps besides those, I'm happy to listen 🙂

**Comment by tobiasKaminsky** [comment]
> I don't have a lot of experience with Wayland, sorry. It seems that KDE does not support the necessary protocol for `wtype`, just like the error message said: [atx/wtype#34](https://github.com/atx/wtype/issues/34)

Yes, this I read…Sad that this is indeed not yet done.



> Regarding `wl-copy`, could you please try to call it manually and see if that works? I think `echo "👌" | wl-copy` should do it.

This works. It is then in my KDE clipboard (klipper)

But with above script or with:
rofimoji --clipboarder wl-copy

It is not in klipper.

**Comment by fdw** [comment]
Unfortunately, I don't have a real idea what the problem could be. But I've pushed something to the branch `fix/wl-copy` that might, with a bit of luck, fix it. Could you please try that?

**Comment by tobiasKaminsky** [comment]
Many thanks for your help!
I installed poetry, ran poetry build and installed it via "pip install dist/rofimoji-6.0.0.dev0-py3-none-any.whl
Prior to that I uninstalled system-wide/old rofimoji.

I then called script which contains:
#!/bin/zsh
/home/tobi/.local/bin/rofimoji --action type clipboard --clipboarder wl-copy

But still no luck :S
If you need me to debug something, I can try, though I am not experienced at all in python (but developing in general)

**Comment by fdw** [comment]
Thanks for the offer 🙂

Could you please try `--action copy`? `clipboard` is meant to insert using (probably) `wtype` (which doesn't work) and then restore the original clipboard. Maybe it's lost somewhere in there...

**Comment by tobiasKaminsky** [comment]
💙🤞
Wow! This works 💪💪💪💪

**Comment by fdw** [comment]
Awesome!

Then I guess it's only the missing compatibility of KDE. If you have an idea for an alternative to `wtype`, please share 🙂

**Comment by tobiasKaminsky** [comment]
Unfortunately not. I digged a bit around and nothing found.
For me it is still okay, as I previously (with X11) also only copied and then pasted it.

Many thanks!

**Comment by fdw** [comment]
Thanks, but I only guess, since I'm still on Xorg 😉

Feel free to open a new ticket and describe your problem there, @asklow 🙂
